name: Release

on:
  push:
    branches:
    - release

jobs:
  terraform-release:
    if: github.ref == 'refs/heads/release'
    name: 'terraform:release'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        branches: |
          [
            'release'
          ]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
